<?php

/**
 * @file
 * Install, update and uninstall functions for the Comment module.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\field\Entity\FieldStorageConfig;

/**
 * Implements hook_uninstall().
 */
function cambio_turno_ata_uninstall() {

  // ID of webform to delete.
  $webform_id = 'cambio_turno_ata';
  $webform_entity = \Drupal::entityTypeManager()->getStorage('webform')->load($webform_id);
  if (!is_null($webform_entity)) {
    $webform_entity->delete();
  }
}
